### ISSUE TITLE
Springboot fails to build in Codewind on Eclipse Che on OCP4.2

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-foundation#129]
- Follow https://www.eclipse.org/codewind/installoncloud.html to install Codewind on Eclipse Che on OCP4.2
- Add Kabanero 0.3.0 rc3 collections https://github.com/kabanero-io/collections/releases/download/0.3.0-rc.3/kabanero-index.json to the Codewind template
- Create a default Spring boot project and it failed to build with error
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.1.0:resources (default-resources) on project default-application: Cannot create resource output directory: /project/user-app/target/classes -> [Help 1]`
- Below is the full log:
```
Running development environment...
[Warning] Failed to check prerequisites: docker does not seem to be installed or running - failed to execute docker ps
Pulling docker image kabanero/java-spring-boot2:0.3
Running command: buildah pull kabanero/java-spring-boot2:0.3
Getting image source signatures
Copying blob sha256:50d4ee53d49bd59499864f0e9bfc6579df30d0bbd1abf41bcd2adab77584b5db
Copying blob sha256:c585fd5093c62ee42a56af6c09813ac8384d8145c4285bc62c357b41224b1970
Copying blob sha256:b8549e1490f374fc0db048e10647dbb4a430eef20d3004acc45351dbb75a6f9b
Copying blob sha256:3db26d862aa4f15a1977db6fadd5f48b31907e235590f55405484bc21d971272
Copying blob sha256:e61d8721e62e50814b162c8341bb235d3453b9c95bd26439bf9100fcf88338c7
Copying blob sha256:c2f5d76c4dd7f827bac47e9e42ea6b295a2862bd57e50c74576acc1bd7b22192
Copying blob sha256:f6ad6c8bd0c0cf4ed9e1982dfe17a6f0e41c758bc7785450824853f827e1acab
Copying blob sha256:7889f4800adf3b519cc5f65c6e97f30fdc4647e96b1c36c7bbe417178f3ebb5d
Copying blob sha256:886f70c367f85eebffcf27e76d019e9a5f653ecf033f3d9656e616af6a1427df
Copying blob sha256:927f62032e67f84c4a8b349ee12bae7b9ad4f058c359a724e840960c16794090
Copying blob sha256:acb89b62ba06f661bb56c0ba21ff528541d51037263d76bd9ceaffd386d12690
Copying blob sha256:a9a7af1aeb11f29c326c9cdcbf1ac7ee43cd3052d5d57da9ae1c7a70e4205d76
Copying blob sha256:2f8df1fa646b30be02404656203fddc7bab9d9bbea31502eee9e2d99cb3e0592
Copying blob sha256:df54c29e17693c07d0757ec9800bea9ed6a0b51e71b2217296213498641d5f2b
Copying blob sha256:41600dac001486f3d3b170377adff4a7868a4b6e8459d5d999e16f8317e5ef7d
Copying blob sha256:24a707b3325eabc4c06a8214f395c57bdd0449f5ed3dc20658cea14618410d92
Copying blob sha256:75b3f4be4de1828a4c7d0b7f9931cd57ed68ad06c52f0657784cc5f5715724eb
Copying blob sha256:21990857fbaea1ac82ee7b9224304d59107a6bacddf82ff86a323ec7b6d76867
Copying blob sha256:d414be38bc086bb13534fc189572cd00c0e5f27c53fd51af7c6609af4f42485b
Copying config sha256:34cc632a18a7ffb57cbe8bb84cb126a3876d61635752d6aa85e89f7c11bc5ceb
Writing manifest to image destination
Storing signatures
34cc632a18a7ffb57cbe8bb84cb126a3876d61635752d6aa85e89f7c11bc5ceb
[Warning] Could not mount /root/.m2/repository:/mvn/repository because the local file was not found.
[Warning] Could not mount /root/.m2/repository:/mvn/repository because the local file was not found.
Attempting to apply resource in Kubernetes ...
Running command: kubectl apply -f /codewind-workspace/springboot-proj/app-deploy.yaml
Attempting to apply resource in Kubernetes ...
Running command: kubectl apply -f /codewind-workspace/springboot-proj/app-service.yaml
Getting the logs ...
Running docker command: kubectl logs deployment/cw-springbootproj-2fcc7f00-027d-11ea-afc2 -f --pod-running-timeout=2m
[Container] Error from server (BadRequest): container "cw-springbootproj-2fcc7f00-027d-11ea-afc2" in pod "cw-springbootproj-2fcc7f00-027d-11ea-afc2-7c95d6c464-lvmpw" is waiting to start: ContainerCreating
Getting the logs ...
Running docker command: kubectl logs deployment/cw-springbootproj-2fcc7f00-027d-11ea-afc2 -f --pod-running-timeout=2m
[Container] Error from server (BadRequest): container "cw-springbootproj-2fcc7f00-027d-11ea-afc2" in pod "cw-springbootproj-2fcc7f00-027d-11ea-afc2-7c95d6c464-lvmpw" is waiting to start: ContainerCreating
Getting the logs ...
Running docker command: kubectl logs deployment/cw-springbootproj-2fcc7f00-027d-11ea-afc2 -f --pod-running-timeout=2m
[Container] Error from server (BadRequest): container "cw-springbootproj-2fcc7f00-027d-11ea-afc2" in pod "cw-springbootproj-2fcc7f00-027d-11ea-afc2-7c95d6c464-lvmpw" is waiting to start: ContainerCreating
Getting the logs ...
Running docker command: kubectl logs deployment/cw-springbootproj-2fcc7f00-027d-11ea-afc2 -f --pod-running-timeout=2m
[Container] Error from server (BadRequest): container "cw-springbootproj-2fcc7f00-027d-11ea-afc2" in pod "cw-springbootproj-2fcc7f00-027d-11ea-afc2-7c95d6c464-lvmpw" is waiting to start: ContainerCreating
Getting the logs ...
Running docker command: kubectl logs deployment/cw-springbootproj-2fcc7f00-027d-11ea-afc2 -f --pod-running-timeout=2m
[Container] Error from server (BadRequest): container "cw-springbootproj-2fcc7f00-027d-11ea-afc2" in pod "cw-springbootproj-2fcc7f00-027d-11ea-afc2-7c95d6c464-lvmpw" is waiting to start: ContainerCreating
Getting the logs ...
Running docker command: kubectl logs deployment/cw-springbootproj-2fcc7f00-027d-11ea-afc2 -f --pod-running-timeout=2m
[Container] Error from server (BadRequest): container "cw-springbootproj-2fcc7f00-027d-11ea-afc2" in pod "cw-springbootproj-2fcc7f00-027d-11ea-afc2-7c95d6c464-lvmpw" is waiting to start: ContainerCreating
Getting the logs ...
Running docker command: kubectl logs deployment/cw-springbootproj-2fcc7f00-027d-11ea-afc2 -f --pod-running-timeout=2m
[Container] Running command:  /project/java-spring-boot2-build.sh run
[Container] Installing parent dev.appsody:spring-boot2-stack:0.3.15
[Container] > mvn install -q -f /project/appsody-boot2-pom.xml
[Container] Build and run project in the foreground
[Container] > mvn -Dmaven.test.skip=true clean spring-boot:run
[Container] [INFO] Scanning for projects...
[Container] [INFO] 
[Container] [INFO] ------------------< dev.appsody:default-application >-------------------
[Container] [INFO] Building default-application 0.0.1-SNAPSHOT
[Container] [INFO] --------------------------------[ jar ]---------------------------------
[Container] [INFO] 
[Container] [INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ default-application ---
[Container] [INFO] 
[Container] [INFO] >>> spring-boot-maven-plugin:2.1.6.RELEASE:run (default-cli) > test-compile @ default-application >>>
[Container] [INFO] 
[Container] [INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ default-application ---
[Container] [INFO] Using 'UTF-8' encoding to copy filtered resources.
[Container] [INFO] ------------------------------------------------------------------------
[Container] [INFO] BUILD FAILURE
[Container] [INFO] ------------------------------------------------------------------------
[Container] [INFO] Total time:  19.349 s
[Container] [INFO] Finished at: 2019-11-08T23:14:31Z
[Container] [INFO] ------------------------------------------------------------------------
[Container] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.1.0:resources (default-resources) on project default-application: Cannot create resource output directory: /project/user-app/target/classes -> [Help 1]
[Container] [ERROR] 
[Container] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[Container] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[Container] [ERROR] 
[Container] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[Container] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[Container] Wait received error on APPSODY_RUN/DEBUG/TEST exit status 1
```

**Comment by ebullient** [comment]
I don't know why any steps in this flow are running as root.

34cc632a18a7ffb57cbe8bb84cb126a3876d61635752d6aa85e89f7c11bc5ceb
[Warning] Could not mount /root/.m2/repository:/mvn/repository because the local file was not found.
[Warning] Could not mount /root/.m2/repository:/mvn/repository because the local file was not found.

This is trying to create and mount the  .m2 directory for the root user. An environment variable to specify the home directory to use is not being set to prevent this behavior.

**Comment by makandre** [comment]
We don't mount the host's m2 dir when running in Codewind, whether locally or on Che.  But those warnings shouldn't affect the stacks ability to build.

The user's app directory is mounted, perhaps it's some permission error here?

**Comment by makandre** [comment]
I just tried it, created a project using springboot stack from the built-in appsodyhub/incubator repo, that built fine.

But a project using the springboot stack from the Kabanero collection above failed with the same error Tam reported.  So there's something different with that stack

**Comment by chilanti** [comment]
Agree w/ @makandre. Both stacks (the `kabanero/java-spring-boot2:0.3` and `appsody/java-spring-boot2:0.3`) have the same `APPSODY_MOUNTS` env var, which includes the infamous entry `~/.m2/repository:/mvn/repository`. In  all cases, Appsody on Kube will attempt to mount this off the current user $HOME dir (`/root`) - but, since it's not found there, the mount fails with a warning. This is a benign situation, because - yes - a "real" user may not even have maven installed (and therefore may not have `.m2` anywhere on the system). When this happens, the container will go on its merry way, storing the maven dependencies in `/mvn/repository` (on the container file system). The build IMHO is failing because of some other issue in the Kabanero `pom.xml` - nothing to do with the `.m2` mount.

**Comment by ebullient** [comment]
Back to this, then: [Container] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.1.0:resources (default-resources) on project default-application: Cannot create resource output directory: /project/user-app/target/classes -> [Help 1]

**Comment by makandre** [comment]
There is difference with the permissions on the `project` folder.

For appsody stack, it's:
```
drwxr-xr-x.   1 root root   22 Oct 14 11:09 project
```

For kabanero stack, it's:
```
drwxr-xr-x.   1 java_user java_group 255 Nov  8 17:21 project
```

**Comment by kilnerm** [comment]
Part of the requirements for the kabanero base images was that they would pass the RH certification process, to do that the containers cannot be running as the root user, hence the difference in ownership.

**Comment by BarDweller** [comment]
`his is a benign situation, because - yes - a "real" user may not even have maven installed (and therefore may not have .m2 anywhere on the system).`

The stack init scripts check for the missing .m2 directory and create it when required, ensuring that even users who do not have maven installed locally, will have the directory for the mount to use. 

There seems to be something odd here in how Codewind is running the stack, because if the stack is being run as the current user (non-root), then we wouldn't expect to see appsody try to mount root's m2 cache folder. Yet, if the stack is being run as root, then we'd expect the init script to have created the missing m2 cache folder. Either way you look at it, something is wrong here about how the stack is being used vs how it was designed. Whether that misbehavior is affecting this particular issue or not, may be a different question, but I think it's demonstrative that Codewind is not executing appsody stacks the same way that appsody does, which leaves open the door for Issues like this one.

**Comment by chilanti** [comment]
The difference is in the stack Dockerfile. Kabanero has the following lines, which the correspondent Appsody stack doesn't:
```
RUN chown -R java_user:java_group /project
RUN chown -R java_user:java_group /config
RUN chown -R java_user:java_group /mvn
```

**Comment by makandre** [comment]
Suggested by @chilanti, when I shell into the container and run the entrypoint as `java_user`, it fails with the same error:

```
sh-4.4$ whoami
java_user
sh-4.4$ /project/java-spring-boot2-build.sh run
Installing parent dev.appsody:spring-boot2-stack:0.3.15
> mvn install -q -f /project/appsody-boot2-pom.xml
Build and run project in the foreground
> mvn -Dmaven.test.skip=true clean spring-boot:run
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< dev.appsody:default-application >-------------------
[INFO] Building default-application 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ default-application ---
[INFO] 
[INFO] >>> spring-boot-maven-plugin:2.1.6.RELEASE:run (default-cli) > test-compile @ default-application >>>
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ default-application ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.220 s
[INFO] Finished at: 2019-11-14T16:40:49Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.1.0:resources (default-resources) on project default-application: Cannot create resource output directory: /project/user-app/target/classes -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by chilanti** [comment]
I think we have a root cause. 
The stack has things like `RUN chown -R java_user:java_group /project` in the Dockerfile. However, `/project/user-app` is mounted, as specified in the Dockerfile itself: 
`ENV APPSODY_MOUNTS=".:/project/user-app;~/.m2/repository:/mvn/repository"`
So - it turns out that the user that created the directory that gets mounted over `/project/user-app` is `root` (or whatever user Codewind / Che run under). In my test environment this is apparent:
```
-rw-rw-r--. 1 java_user java_group   628 Nov  8 17:19 mvn-stack-settings.xml
-rwxrwxr-x. 1 java_user java_group  4877 Nov  8 17:19 java-spring-boot2-build.sh
-rw-rw-r--. 1 java_user java_group    69 Nov  8 17:19 .dockerignore
-rwxrwxr-x. 1 java_user java_group   583 Nov  8 17:19 .appsody-init.sh
-rwxrwxr-x. 1 java_user java_group   294 Nov  8 17:19 .appsody-init.bat
drwxrwxr-x. 1 java_user java_group   125 Nov  8 17:21 util
-rw-rw-r--. 1 java_user java_group  6609 Nov  8 17:21 mvnw.cmd
-rwxrwxr-x. 1 java_user java_group 10078 Nov  8 17:21 mvnw
drwxr-xr-x. 1 java_user java_group    21 Nov  8 17:21 .mvn
-rw-rw-r--. 1 java_user java_group  6744 Nov  8 17:21 appsody-boot2-pom.xml
-rw-rw-r--. 1 java_user java_group   757 Nov  8 17:21 Dockerfile
drwxr-xr-x. 1 java_user java_group   255 Nov  8 17:21 .
drwxr-xr-x. 5 root      root         154 Nov 14 17:28 user-app
drwxr-xr-x. 1 root      root          44 Nov 14 17:29 ..
```
Notice that everything under `/project` is owned by `java_user`, but `user-app` is owned by `root`. 
In the local case, (i.e. when Appsody runs on your laptop) everything works fine because - I presume - appsody forces the container to run as the local user, as indicated by this env var in the Dockerfile:
```
ENV APPSODY_USER_RUN_AS_LOCAL=true
```
So - those directories that are mounted over `/mvn/repository` and `/project/user-app` are accessible to the local user. But on Kube, the container really runs a `java_user` as shown above by @makandre - leading to the discrepancy.

**Comment by BarDweller** [comment]
So as suspected, it would seem that indeed Codewind is not executing appsody stacks the same way that appsody does. 

 - Not mounting the m2 dir
 - Not running the stack init script (?tbc, but that script would have created the m2 dir the logs claim not to exist)
 - Not honoring the APPSODY_USER_RUN_AS_LOCAL flag. 
 
The stacks are developed and tested using appsody, effectively Codewind would seem to be trying to act as an independent runtime for those stacks, and is not maintaining compatibility with appsody leading to Issues being reported with the stacks, even though the stacks themselves are fine. 

As a stack author, I wonder what we can do to prevent the time lost to issues caused by alternate appsody runtimes that fail to execute the stacks properly.

**Comment by makandre** [comment]
Codewind is running using `appsody run` actually.

As @chilanti pointed out, we narrowed it down to the permissions over the `user-app` mount.  Continuing to dig into what we can do about that.

**Comment by BarDweller** [comment]
`appsody run` doesn't address the init script/m2 mount concerns. 

But it should mean you'd be getting the behavior of the `APPSODY_USER_RUN_AS_LOCAL` flag. What's different about your use of `appsody run` vs a regular user at a command line ?

**Comment by chilanti** [comment]
@BarDweller - on Kube, `appsody run` doesn't propagate the identity of the pod that ran `appsody init` to the pod where the stack runs. That's where the difference lies. We need to take a step back and evaluate if that's feasible and if that's even a good idea, given that you [the stack] do not control the identity associated with the pods where Che runs.

**Comment by BarDweller** [comment]
When I use `appsody run` to run the kabanero spring stack.. I see it use this command.. 
```
Running docker command: docker run --rm -p 5005:5005 -p 8080:8080 -p 8443:8443 -p 35729:35729 --name ktest-dev -u 1001:1001 -e APPSODY_USER=1001 -e APPSODY_GROUP=1001 -v /home/myuser/Appsody/new-local-build/kabtest/test/ktest/.:/project/user-app -v /home/myuser/.m2/repository:/mvn/repository -v /home/myuser/.appsody/appsody-controller:/appsody/appsody-controller -t --entrypoint /appsody/appsody-controller kabanero/java-spring-boot2:0.3 --mode=run
```

When I exec into the running container, I see `/project` is owned by java_user, and `/project/user-app` is owned by id 1001:1001 (aka 'myuser` on my system, but the userid has no name inside the container). Similarly, the `/mvn/repository` dir is owned by 1001:1001 

The `id` command tells me I'm running as user/group 1001/1001.

How are you avoiding `appsody run` setting the `-u 1001:1001 -e APPSODY_USER=1001 -e APPSODY_GROUP=1001` flags ?

**Comment by chilanti** [comment]
@BarDweller - this is appsody on Kube. As such, it doesn't execute a `docker run`. It generates a `Deployment` and `kubectl apply` it. The project is mounted in a PVC - it's a completely different scenario from the local use case.

**Comment by BarDweller** [comment]
Where are the docs for appsody on Kube? 
The public appsody project only discusses appsody with docker. 
The test cases for all stacks are only driven for appsody with docker. 
Does appsody on Kube have it's own github project ?

**Comment by chilanti** [comment]
@BarDweller - since the only consumer of Appsody on Kube is Codewind/Che, we haven't documented pretty much any of it. There isn't a separate repo.

**Comment by ebullient** [comment]
I think https://github.com/eclipse/codewind/issues/1133 is the fix for this. There is nothing the Spring stack can do here, it is down to how Codewind is launching appsody.

**Comment by BarDweller** [comment]
@chilanti 
Then I would strongly suggest not calling it appsody, because otherwise it leads to the kinds of discussion above, where you claim to be using `appsody run` but really are using `appsody-on-kube run`.

eg.
>Codewind is running using `appsody run` actually.

No, it's not. `appsody run` uses Docker. What you have, is exactly what I'm referring to above, an independent runtime, attempting to maintain compatibility with appsody, but failing to do so. Leading to Issues being raised against stacks, like this one, that are actually the fault of the runtime failing to be 100% compatible with what everyone else calls appsody.

**Comment by BarDweller** [comment]
Since Codewind isn't actually using appsody, and is using appsody-on-kube, and since all appsody/kabanero stacks are only tested using appsody. It would seem to me that Codewind should have it's own repository of stacks that it has tested using appsody-on-kube. 

Using stacks from beyond that repo would be at the users risk, because they may make assumptions that are fine and valid when running on appsody, that would fail on appsody-on-kube.

**Comment by makandre** [comment]
@ebullient yes, there's a PR https://github.com/eclipse/codewind/pull/1136 under going review and testing for 1133.  Will post back once it's in.

**Comment by marikaj123** [comment]
Looking for the fix to be published in codeeind and pulled in CHE in the next release.

**Comment by makandre** [comment]
FYI https://github.com/eclipse/codewind/issues/1133 is verified and closed.

**Comment by tam512** [comment]
Verified that this problem is fixed
