### ISSUE TITLE
ksvc with an ErrImagePull becomes stuck in RevisionMissing state

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-foundation#131]
Due to transient network issues pulling from registry.redhat.io

```
Failed to pull image "registry.redhat.io/openshift-serverless-1-tech-preview/serving-queue-rhel8:0.8.1-4": rpc error: code = Unknown desc = Get https://registry.redhat.io/containers/content/dist/containers/rhel8/multiarch/containers/redhat-openshift-serverless-1-tech-preview-serving-queue-rhel8/manifests/list/0.8.1-4?_auth_=exp=1573840510~hmac=d5f7e8e437108abc13e18891c0b5774e91e60180412e3a95e4a884559d7cd0bb: dial tcp 104.69.48.79:443: connect: connection refused
```

When a ksvc spins up and fails an image pull, it remains in a RevisionMissing state. It does not appear to retry.

**Comment by kaczyns** [comment]
@dacleyra Is this something that we need to discuss with Red Hat (why the Revision is not created / no retry)?

**Comment by marikaj123** [comment]
According to Tim:  I think we are going to have to open a bug against Red Hat to fix this.  There is nothing that we can do to have the red hat server not refuse our connection.

**Comment by kaczyns** [comment]
Someone who can re-create this issue is going to need to open a bug with red hat.
https://access.redhat.com/support/cases/#/case/list

**Comment by marikaj123** [comment]
@stephenkinder - Any idea who can help with opening a bug in RedHat.

**Comment by marikaj123** [comment]
@dacleyra and @tim, Have we opened an issue with redhat?

**Comment by kaczyns** [comment]
@marikaj123 no we have not, someone who can reproduce the issue should open an issue with redhat.

**Comment by marikaj123** [comment]
@dacleyra - Will be open a bug with RedHat.

**Comment by marikaj123** [comment]
According to Tim Kaczynski :
This is an issue that should be opened against either the openshift-serverless operator, or knative serving.  If at all.  The issue probably still exists, but since we don't appear to have transient network issues on fyre anymore, we'll not hit this again

**Comment by marikaj123** [comment]
According to Tim:  it would be unlikely that anyone will hit this issue.  Internally we hit this issue due to some networking problem with our fyre systems that I don't think anyone understands but is fixed now.  It would be extremely rare for a customer to have a failure downloading this container image to the point that this issue occurs.  The issue cannot be reproduced since the fyre issue was resolved. 
If we're going to pursue the issue, then someone needs to re-create the issue.  I'm not sure how to re-create the issue now that our networking problem is fixed.  Then, need to open an issue against the knative/serving github repository.  They will want us to re-create the issue, which we'll have to do because it's so unlikely that anyone else would hit the issue.  And then they'll have to decide whether it's important enough to fix.





Dan opened the issue in the first place, I'd like to hear his comments.

**Comment by marikaj123** [comment]
@gecock and @mtamboli - Do you agree that from SVT perspective the issues does no longer exist.

**Comment by gecock** [comment]
I am fine deferring to developments recommendation given they have debugged it and understand the underlying problem best. Seems like it's a network issue, so if that's the consensus then I'm fine with closing this out as invalid unless told otherwise.

**Comment by dacleyra** [comment]
Case opened
https://access.redhat.com/support/cases/#/case/02561866
