### ISSUE TITLE
install.sh file not available in 0.3.0-rc.1

### ISSUE THREAD

**Issue by debu66er** [kabanero-io/kabanero-foundation#132]
I didn't find the documented install.sh file to install and test 0.3.0-rc.1 release on OCP 4.2
Where should we find it? Thanks!

**Comment by alohr51** [comment]
Hi @debu66er since 0.3.0 isn't released yet you can find all releases in https://github.com/kabanero-io/kabanero-operator/releases the most recent release candidate for 0.3.0 is currently `0.3.0-rc-.3`

You can find the `install.sh` file in the assets dropdown under the release. Please keep in mind its only a release candidate and things may still change before 0.3.0 is officially released.

Let me know if that answers your issue.

**Comment by debu66er** [comment]
Understood. I was looking for it under kabanero-foundation project.
Thanks!
