### ISSUE TITLE
 design mechanism to ensure that each test runs in a "clean" environment in between tests

### ISSUE THREAD

**Issue by garypicher** [kabanero-io/kabanero-foundation#168]
- the gold standard would be to install a fresh environment for each test, which isn't practical
- is there a way to do a "soft reset" of the environment, e.g. reverse whatever the last test case did?
	- if the framework could do this automatically (record what the last test did and undo it) that would be ideal, but i don't know if it's possible
	- at the very least, we can develop best practices for test case writers that instruct them to tear down the environment after the test or something along those lines

**Comment by c1505** [comment]
The scope of this is a little different than the issue I was working on internally.  Internally, it was for the Kabanero install rather than the additional things that an individual test may do.  

I have been looking into potential paths:
* Backup/Restore using openshift's tooling https://docs.openshift.com/container-platform/4.3/backup_and_restore/backing-up-etcd.html 
  * Process is changing a bit with 4.4
  * Current docs aren't working for me and I have a ticket open with red hat to address it
* Require people writing tests to write as a custom resource definition.  
  * my understanding isn't great here, but from what I see, it appears that it would make it easier to rollback changes
* Use the tool boskos that Kubernetes core uses to maintain a clean environment
  * Appears that it manages state by updating the config maps.  It could be used in addition to CRDs https://github.com/kubernetes/test-infra/tree/master/boskos
* Monitor objects created by etcd and do not allow tests that create and don't clean up those objects

**Comment by c1505** [comment]
I will continue to do some research into potential paths.  Currently one of the next steps would be to meet with some additional people who have more experience in these areas.

**Comment by c1505** [comment]
The backup and restore option seems more promising.  I performed a backup, installed Kabanero, applied the CR, performed a restore.  I ran the uninstall script after the restore as a rough way to see what might still be left around.  The only thing I saw was:
```
+ oc adm policy remove-scc-from-user anyuid system:serviceaccount:kabanero:che-workspace
securitycontextconstraints.security.openshift.io/anyuid removed from: ["system:serviceaccount:kabanero:che-workspace"]
+ oc adm policy remove-scc-from-user privileged system:serviceaccount:kabanero:che-workspace
securitycontextconstraints.security.openshift.io/privileged removed from: ["system:serviceaccount:kabanero:che-workspace"]
```
I'll try to verify on another attempt if that is still present after a restore.  
Both the backup and restore procedures a very quick.  Backup is a single command that takes less than a minute.  Restore is more complicated, but it appears to complete in about 5 minutes.

**Comment by marikaj123** [comment]
Restore going to the new reo
