### ISSUE TITLE
Not able to create webhook with tekton dashboard

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-foundation#47]
Using the latest kabanero install, seeing issue creating a webhook from Tekton dashboard.

Thanks @dacleyra for looking into it.

![image](https://user-images.githubusercontent.com/29490950/64188247-09411600-ce40-11e9-8d3c-1f32c05acc28.png)

**Comment by kvijai82** [comment]
I saw this a few times in my test env.  Can you please see if it's a caching issue?  Try in a private window?  That was the first thing the Tekton team told me to check.  Beyond that we had to get some mismatched versions sorted out.

**Comment by mtamboli** [comment]
@kvijai82 I tried the private window and it does not seem to help. It is happening on multiple clusters.

**Comment by jgawor** [comment]
no. the scrip is just using a wrong file for the extensions.

**Comment by jgawor** [comment]
use https://github.com/tektoncd/dashboard/releases/download/v0.1.1/openshift-tekton-dashboard.yaml and https://github.com/tektoncd/dashboard/releases/download/v0.1.1/openshift-webhooks-extension.yaml instead of the generic ones in the https://github.com/kabanero-io/kabanero-foundation/blob/master/scripts/install-kabanero-foundation.sh script.

**Comment by dacleyra** [comment]
In attempting to use the openshift release yaml, accessing the dashboard returns a 502

**Comment by dacleyra** [comment]
corrected in install script
