### ISSUE TITLE
Installation script instructions need embellishing

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-foundation#82]
On this page, in the `Installation` section:

https://kabanero.io/docs/ref/general/installing-kabanero-foundation.html

I don't see any mention of copying and modifying:

https://github.com/kabanero-io/kabanero-operator/blob/master/config/samples/full.yaml

prior to running the install-kabanero-foundation.sh script

**Comment by mtamboli** [comment]
Step 3 which is added recently to the doc assumes that the updates are being made to full.yaml. None of the Kabanero install docs talk about how this file is used.  https://github.com/kabanero-io/docs/blob/master/ref/general/collection-building.adoc

**Comment by bschrammIBM** [comment]
I opened https://github.com/kabanero-io/docs/issues/103 to track this update in the /docs repo.

**Comment by alohr51** [comment]
@bschrammIBM is https://github.com/kabanero-io/docs/issues/103 a duplicate issue of this? We should try to no duplicate issues. You can move/transfer this issue to the docs repo if that was your goal (bottom right of this issue)

**Comment by kaczyns** [comment]
This page:
https://kabanero.io/docs/ref/general/installing-kabanero-foundation.html
reads to me like a basic getting started / install page.  I think that if we try to talk about modifying the default kabanero yaml here it will be confusing for the people that just want to get started.  Maybe we could say at the end of the install script section something like:

"This will install Kabanero with default settings using the default collections (link to collections).  If you would like to use a different set of collections, see here (link to doc about how to curate the collection)".

That seems like a compromise to me between keeping the page simple for new folks, but also reminding experienced users that they have some editing to do if they want to deploy an Nth Kabanero using collections that they've already curated.

**Comment by mtamboli** [comment]
@kaczyns I agree with your comment above to keep the default install simple. But my understanding is that you still need to do some customization (full.yaml git updates for security) before installing Kabanero to be able to use Kabanero CLI later. Can that be done easily later if user wants to use Kabanero CLI?

**Comment by kaczyns** [comment]
@mtamboli My understanding is that you can't use the CLI until you've cloned and curated the collections, because Champ will be unable to add himself as an admin to the kabanero-io hosted collections.  I don't think there is a reason to customize the configuration (full.yaml) until Champ has curated the collections, and at that time the following things need to be updated:
1) URL of the collection
2) Github org that the admins for the collection are in
3) Github team(s) that admin the colleciton
4) API URL of the github where the org/teams are

It's pretty easy, the user can either edit the `Kind: Kabanero` that the install produced, on their cluster, or they can delete it and create a new one using the full.yaml as a model.  Editing is as simple as `oc edit kabanero kabanero` (the default name) and then a text editor pops up and they change the url, etc.  Or they could edit it in the OKD console.

**Comment by mtamboli** [comment]
That helps! So it is matter of getting the documentation at the appropriate place. So collection curation and GitHub setup as part of that is a pre-req for Kabanero CLI? So Install doc can just provide links to those as you mentioned.

**Comment by davco01a** [comment]
@mtamboli @kaczyns It maybe simple to `oc edit kabanero kabanero`, but agree with Monica in lieu of clear, sequenced documentation on cloning the index.yaml, copy and modifying full.yaml, setting up git teams and members located in one central place, it will be a mystery to consumers who want to be able to actually use the functionality of the Kabanero CLI

**Comment by bschrammIBM** [comment]
Issue moved to [kabanero-io/docs #107](https://github.com/kabanero-io/docs/issues/107) via [**ZenHub**](https://www.zenhub.com/)
